version: '3.1'
services:
  db:
    platform: linux/x86_64
    hostname: mysql
    image: mysql:8.0.27
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
  adminer:
    hostname: mysql
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8580:8080


volumes:
  db_data: